### ISSUE TITLE
Production Docker image documentation

### ISSUE THREAD

**Issue by darthtrevino** [primeroIMS/primero#111]
Hello 👋,
I'm trying to configure a cloud instance of Primero into an Azure App Service using the `primeroims/application`  image available on DockerHub.  The environment variables I'm using are: 

```yaml
APP_SHARE_DIR: /share/public
DEVISE_JWT_SECRET_KEY: <random token>
DEVISE_SECRET_KEY: <random token>
LOCALE_ALL: en,es
LOCALE_DEFAULT: en
PRIMERO_HOST: <deployed hostname>
PRIMERO_MESSAGE_SECRET: <random token>
PRIMERO_SECRET_KEY_BASE: <random token>
POSTGRES_HOSTNAME: <postgres hostname>
POSTGRES_DATABASE: <postgres database>
POSTGRES_USER: <postgres user>
POSTGRES_PASSWORD: <postgres password>
POSTGRES_POOL_NUM: 10
POSTGRES_SSL_MODE: require
SOLR_HOSTNAME: <solr ip address>
```

I'm able to get the image running, but it's missing some key assets (most assets under public/). It looks like the public folder is mounted in the Nginx container in development mode. 

How should this application be deployed in a production environment? Can the `primeroims/application` image be used on its own like this? If not, do you have a kubernetes configuration?

Thanks! 
Chris

**Comment by darthtrevino** [comment]
Here's the asset failures in the browser: ![primero_docker_image](https://user-images.githubusercontent.com/113544/141212928-f35f0adb-a734-48f6-beff-8287a073cd11.png)

**Comment by pnabutovsky** [comment]
When running this on Azure/K8s, we skip Nginx, and instead use an Azure Gateway that reverse proxies all requests, event the static asset ones to Primero. Primero Rails runs in a special mode that allows it to serve the static assets. \ To enable that mode, you need to make sure that the container has the environment variable `RAILS_PUBLIC_FILE_SERVER=true`. 

If you want to use Nginx to reverse proxy and serve the static assets, make sure there is a shared volume between the applucation container, mounted on `/share/public` and the Nginx container, mounted on `/srv/primero/application/public`. 

When orchestrating your deployment, you can imitate what we do in Docker Compose (see the `docker/docker-compose.yml` and `docker/docker-compose.prod.yml`).

**Comment by darthtrevino** [comment]
That's perfect, thanks again Pavel!
