### ISSUE TITLE
Conditional Fields

### ISSUE THREAD

**Issue by Khizar-Hussian** [primeroIMS/primero#117]
Primero lacks the support for conditional fields. That is to say, we can not conditionally make a field render, depending on the user choices in the previous field, say a checkbox or radio buttons. We would like to know the recommended method for adding this functionality across the application. We want to refrain from adding the functionality manually to each field where this is required.

**Comment by RobertMacTavish** [comment]
Please see:
https://github.com/primeroIMS/primero/blob/develop/doc/evaluated_expressions.md

**Comment by Khizar-Hussian** [comment]
@RobertMacTavish Thank you so much for the response!
Would you also kindly link me to a relevant doc for achieving conditional functionality on dropdowns. The basic idea is to have either 
1. Successive dropdowns whose fields are dependent on the choice in the previous dropdowns, or
2. Have one massive cascading dropdown, there will be main fields and subfields, and selecting a subfield would automatically select the main field.

A very crude representation of what we're trying to achieve is attached as an image to this response. If you could point us in the right direction, that would be great!

![image](https://user-images.githubusercontent.com/34032481/150924988-9a79ea19-05cd-4d12-b442-4e7a1b14493c.png)

![image](https://user-images.githubusercontent.com/34032481/150925072-58327779-7ab5-4632-a39e-3ccc64802620.png)

**Comment by pnabutovsky** [comment]
@Khizar-Hussian You are looking for conditional select options. That should be in the documentation link that was shared with you. Note that skip logic and conditional selects are not available for configuration via the UI. You need to set up a Ruby script to load it. See the link below for samples: https://github.com/primeroIMS/primero/tree/develop/db/configuration. 

In Primero you will want to implement 2 separate fields. For example you may want to have a multiselect `violence` field with options values coming from a Primary Violence Type lookup:`['physical_violence', 'mental_violence', 'neglect']`. You will then need to define a lookup Secondary Violence Type lookup with values tagged according to the Primary Violence type. Eg:

```
Lookup.create_or_update!(
  unique_id: 'lookup-secondary-violence-type',
  name_en: 'Secondary Violence Type',
  lookup_values: [
    { id: 'beating', display_text: 'Beating, tags: %w[physical_violence] },
    { id: 'biting', display_text: 'Biting', tags: %w[physical_violence] },
    { id: 'physical_neglect', display_text: 'Physical Neglect', tags: %w[neglect] },
    ...
  ]
)
```

Lastly, you will need to define a `violence_secondary` field that displays options based on the `violence field. Something like:

```
Field.new(
  name: 'violence_secondary',
  type: 'select_box',
  display_name_en: 'Secondary Violence',
  option_strings_source: 'lookup lookup-secondary-violence-type',
  option_strings_condition: {
    'physical_violence' => { 'eq' => { 'violence' => 'physical_violence' } },
    'mental_violence' => { 'eq' => { 'violence' => 'mental_violence' } },
    'neglect' => { 'eq' => { 'violence' => 'neglect' } }
  }
```
