### ISSUE TITLE
Need fix for "2.6.2-compliant syntax, but you are running 2.6.5" warnings.

### ISSUE THREAD

**Issue by aashimgarg** [primeroIMS/primero#28]
While starting the rails server we get this warning. There is a need to fix this warning.
@IanLawrence which version of parser gem would be best suited to fix this warning.

**Comment by pnabutovsky** [comment]
As long as the major/minor versions are aligned this is not an issue. This is a thoroughly benign expected behavior of `whitequark/parser`. See: https://github.com/whitequark/parser#compatibility-with-ruby-mri
