### ISSUE TITLE
Usersnap Feedback - Another test from NY

### ISSUE THREAD

**Issue by IanLawrence** [primeroIMS/primero#3]
**Sender**: hotpants@aol.com
**Comment**: Wow this is cool! Does it work?
[Open #4 in Usersnap Dashboard](https://usersnap.com/a/#/company/p/primero-d2bf7cbe/4)

<a href='https://usersnappublic.s3.amazonaws.com/2016-11-14/22-45/7dd5f7c4-b5bd-4ce4-b37e-b2d05ea0e2a3.png'>![Usersnap Feedback - Another test from NY](https://usersnappublic.s3.amazonaws.com/2016-11-14/22-45/1285c059-63ec-4c39-b2ae-eb20699756f1.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2016-11-14/22-45/7dd5f7c4-b5bd-4ce4-b37e-b2d05ea0e2a3.png'>Download original image</a>

**Browser**: Chrome 54 (Windows 8.1)
**Referer**: [https://nibbed.io/login](https://nibbed.io/login)
**Screen size**: 1536 x 864 **Browser size**: 1520 x 695

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by IanLawrence** [comment]
This screen looks totally normal.What seems to be the problem? (test comment)

**Comment by RobertMacTavish** [comment]
Depends on what you call normal... (test reply to test comment)

**Comment by IanLawrence** [comment]
Test issue
