### ISSUE TITLE
Extremely Outdated Production Deployment Procedures and Documentation

### ISSUE THREAD

**Issue by thiras** [primeroIMS/primero#50]
Hello,

The offical way of production grade deployment of the primero is EXTREMELY outdated.

ChefDK, which is the main tool for deployment, is deprecated. Check the `Deprecated Products` section on [official site](https://downloads.chef.io/).

![Screenshot from 2020-10-22 21-28-30](https://user-images.githubusercontent.com/5150432/96914475-b98f3500-14ad-11eb-946e-7a9a47349b67.png)

[Knife-solo](https://github.com/matschaffer/knife-solo) is also deprecated. Check it's readme;

```
DEPRECATED

This gem has officially fallen too far behind the curve of current Chef releases & workflows.

Please consider using https://knife-zero.github.io/, ansible, or visit https://www.chef.io/ for other ideas.
```

Official recommended OS for the deployments is Ubuntu 16.04 which has an End-of-Life date in 6 months.

Besides all of these, VirtualBox and Vagrant usage is in constant fall against Docker and Kubernetes. Nobody wants to keep entire OS for an application nowadays.

And for last, (I didn't tested or check but) #20 mentions about a security issues for CoachDB cookbook.

I would like to help the project to update deployment procedures and documentation.

What do you think about those issues and what "modern" deployment strategy would you prefer to update the project? I would like to hear from you. 

This is a great project and I wouldn't want see it dead just because of lack of maintainance for deployment procedures.

**Comment by pnabutovsky** [comment]
Primero is alive and kicking! Development for version 2 is under way, and you can review the progress here: https://github.com/primeroIMS/primero/tree/development_v2. The new stack uses Docker to manage deployments, has abandoned CouchDB for PostgreSQL, and has completely re-written the front end.

**Comment by thiras** [comment]
Hooray! This is HUGE news. Thanks for the fast reply and great news.

I'd like to ask about current state of v2. Is it stable enough to deploy and which percentage of the v2 roadmap has completed?

I don't want to seen too pushy but we really need this application at our NGO. I'd like to take the production grade deployment risk (since will be used internally only) if the roadmap covered above +80% and relatively stable enough.

**Comment by pnabutovsky** [comment]
Primero v2 is effectively in Beta: so stable-ish. This current cycle of development is addressing the very thing you are interested in: deployability. Keep an eye out for the folder `ansible` to appear in the root within the next week or so. We would be grateful for multiple pairs of eyes on self-service deployments, and always welcome PRs. You can also check out https://community.primero.org/
