### ISSUE TITLE
Error While Connecting from Android App

### ISSUE THREAD

**Issue by talalanwar09** [primeroIMS/primero#63]
I hope this finds you well. 

We have deployed a primero v1.7 instance here and its working fine on browser:
https://primerouat.septemsystems.com/ 

When we install the app from Play store and try to connect it using Android app it gives the following error.

![WhatsApp Image 2021-03-31 at 10 32 19 PM](https://user-images.githubusercontent.com/34574431/113186565-45816600-9271-11eb-8692-0968390e1304.jpeg)

Can anyone help us on priority basis. 

Regards,
Talal Anwar

**Comment by IanLawrence** [comment]
Is there a specific reason you are running 1.7? the main release is now v2 and this is a PWA so does not need the mobile. I would suggest using that. If not and you want to try other versions of the android app they are here https://github.com/primeroIMS/rapidreg/releases

**Comment by talalanwar09** [comment]
Thank you @IanLawrence for your response, We are currently using v1.7 and soon going to migrate everything to v2.0 may be in 2 Months.
It is very important for us to use the android app for v1.7 at this stage. We will try the other android releases.

If someone can help in fixing the issue, will really appreciate that.

**Comment by IanLawrence** [comment]
You could also try to use Debug APK from android studio and find out why the call to /login is not working. My guess is something network related

**Comment by talalanwar09** [comment]
This is to let you know, That this issue has been resolved from our end. It was SSL certificate issue.
